### ISSUE TITLE
44.1KHz audio do not play back at correct rate

### ISSUE THREAD

**Issue by ghollingworth** [FiveNinjas/SliceOS#1]
Currently the 44.1 KHz range of frequencies are not being played back correctly

**Comment by Bleep42** [comment]
Hi, is this the same as my problem, where playing a wma music file sounds fine through HDMI but played back through the analogue port it's played back faster and higher pitch, like in the olden days when you could speed up your gramophone record? If not, let me know and I'll raise a separate issue.

**Comment by ghollingworth** [comment]
Yes that is the same problem, it has now been fixed in the nightly release.  Can you please confirm the fix and close this issue?

Thanks

**Comment by Bleep42** [comment]
Hi Gordon, update rev.  20150327072056
Much improved, but not quit correct yet. :-(
I could still hear a slight difference between HDMI audio output and snd_rpi_audiotime........ so I ran a tune in sync with the original CD and; I know it'll sound anal, but there is approximately a 1 second speedup for every minute of play. That is, the analogue audio output from the Slice is gaining 1 second for every 1minute of music played,  not much I realise, but audible & I do not in any way consider myself to be an audiophile, who apparently have magic ears! ;-) 
This is playing wma music files, which of course no self respecting audiophile would ever listen to anyway!

**Comment by cecemf** [comment]
Bleep42 have you tried with different file format like aac or MP3 ?

**Comment by Bleep42** [comment]
Hi,  mp3 files are the same.
 It's very easy to check, without even without listening, you can simply run a watch against the play time on the screen.

**Comment by ghollingworth** [comment]
Yes I was hoping to postpone a full clock reconfiguration scheme but it looks like I'm not going to get it!  Just going to sort this out now and hopefully you should get accuracy back

**Comment by ghollingworth** [comment]
@Bleep42 Can you try the Bloody release please...  I think this should now be 100% correct

**Comment by Bleep42** [comment]
Hi Gordon,
Well as I said I haven't got audiophiles 'magic' ears, but it now sounds perfect to me :-)
I know you'll hate me for this, ;-( but will we be able to play Analogue and HMDI together?
Otherwise you can close as far as I'm concerned.
Regards,
Kevin.

**Comment by ghollingworth** [comment]
Unfortunately it is not currently possible to play Analogue and HDMI together, one of the problems is to do with synchronisation...

Basically we have one audio and one video time scale, it is vitally important that the timescales are held in check because the two things that clock out audio and video are not always the same....  Therefore it is possible to require resampling the audio track to iron out these differences.

There are occasions when you may notice this, starting a video for example sometimes you notice the audio track slows down a little bit at the very beginning.

The problem with this resampling is that you'd have to do it for every audio output separately to keep them separately in sync with the video, which means extra work!

Thanks

Gordon

**Comment by Bleep42** [comment]
Hi Gordon,  these changes aren't present in the current nightly build! Please reinstate this bug report until the fixes are present in a released build. 
Regards Kevin.
