### ISSUE TITLE
Subtitles OFF by default.

### ISSUE THREAD

**Issue by cooltempo** [FiveNinjas/SliceOS#11]
As discussed with Gordon - it would be best to have the subtitles turned off by default. This would just be a case of changing the entry in guisettings.xml>defaultvideosettings>showsubtitles to false - see image below.

![screen shot 2015-03-23 at 21 51 06](https://cloud.githubusercontent.com/assets/3112719/6791453/f4058d92-d1a6-11e4-9e63-4638bd18781e.png)

**Comment by cecemf** [comment]
Oh yes please ! it's been annoying me :)

**Comment by ghollingworth** [comment]
So this has been fixed but will only be evident for new installations, unless you completely wipe your library and everything.

Gordon

**Comment by cecemf** [comment]
How do I go wipe the SLICe clean to be able to enjoy the Subtitle OFF ? It's so annoying me right now ! grrrr

**Comment by cooltempo** [comment]
Just turn off subtitles in the video you are watching and save that setting as default. Bingo! No more subtitles.
