### ISSUE TITLE
Internal clock loosing an hour after power off/reboot. 

### ISSUE THREAD

**Issue by Bleep42** [FiveNinjas/SliceOS#13]
With no network connection, every time the Slice is powered off, (remove electrical power) the internal real time clock looses 1 hour, my RTC is now 5hrs behind actual time!. It then doesn't seem to correct itself once it has got a network connection, that is, while you have the connection it's correct, but power it off and power back on without network and its even further wrong. (now 6hrs behind after testing that) 
It seems that if I use the WiFi dongle the time will eventually be corrected in the RTC, but if I only use the ethernet cable it never updates the RTC. 
The time is being updated, in that the minutes are correct, it's just the hours.
PS I think this has only started since BST kicked in.
PPS My Internationalisation is London/UK.

**Comment by ghollingworth** [comment]
Interesting, will have a look later

**Comment by cecemf** [comment]
Strange I didn't have any issues. My time didn't change that's because in my international settings. British time wasn't select. Once done that it went back to normal. Maybe at setup stage it should ask for country and time zone.

**Comment by Bleep42** [comment]
While doing these log files for a different problem, I realised that they show the clock problem very clearly. They were taken in the order 1_, 2_, 3_. If you look at the time logging in the file you will see that the hour has gone backwards in each of the files, I only rebooted the slice for each test, so powering off is not necessary. I had no network connectivity.
https://www.dropbox.com/sh/ulvcmkbwofwtbwa/AAD0CPWSbOf6vOWLPdaHKW3wa?dl=0
Regards, Kevin.

**Comment by Bleep42** [comment]
Hi Gordon, 
Do I assume that you don't think this is a software fault? 
In which case please can you give me details of how I return my Slice for repair. 
Regards Kevin.

**Comment by Bleep42** [comment]
As an experiment I've tried Confuence, to see if it made any difference. (it doesn't)
With no network connection, it took 4 reboots until I started to get the time going backwards by an hour. I then plugged in the Ethanet cable and the time on the screen instantly corrected, (I did not have any time servers set!) however on subsequent reboots with this same configuration, the time continued going backwards from where it had been, ie already an hour out, by an hour at a time, so now 2 hours out. I then set a time server under NTP time servers. Again the time instantly corrected on the screen, without changing anything, on subsequent reboots the time continued going backwards, again from where it had been. 
There seems to be 2 problems. 
1) it seems that the internal real time clock is not being updated from the NTP over a wired network connection, though on the first time, the screen clock is corrected temporary. 
2) rebooting with no network, or only wired network (or a wired with a WiFi connection) causes the internal clock to go backward an hour at a time. (not necessarily every reboot however) 

NB a WiFi only network connection will eventually correct the internal RTC, but it takes a while, l can't say how long and only if you don't have a wired Ethanet connection as well. (presumably the wired connection takes priority?) 

Hope this is of use. If you'd like any testing, or logs I'd be happy to help. (I write real time software for commercial aircraft flight simulation in 'C' so have plenty of experience of nasty little bugs ;-) 
Regards Kevin.

**Comment by Bleep42** [comment]
On latest bloody (Kodi 15.0) build this problem seems to have been resolved. I did try going back to Slice stable and it re-occurred, returned to Slice bloody Kodi 15.0 and the clock worked correctly again.
Presumably you have found something and fixed it?
Regards, Kevin.

**Comment by ghollingworth** [comment]
Ah, I did change something on the bloody build which I thought may be the problem although hadn't held out hope!  Looks like it did the trick!  Basically I removed a hack I inserted to get it working !

Hack gone - problem gone, as is so often the way!

Gordon

**Comment by Bleep42** [comment]
Hi Gordon,
Ok, I've also checked this on Mike Buzz's build of Kodi 15.1 which I believe is bloody build plus some more recent commits, and the clock seem to be fine there as well. :-)
As you've made a change that has probably fixed it, shall I go ahead and mark this as resolved, if you're happy with that.
Thanks Kevin.

**Comment by Bleep42** [comment]
Clock now working as expected, currently on bloody only, soon to be migrated to nightly and stable.
