### ISSUE TITLE
Ability to update to latest stable version of Kodi

### ISSUE THREAD

**Issue by ninyule** [FiveNinjas/SliceOS#21]
I believe that this function has not been enabled yet?

I think this needs to be as simple as possible, for me and the non-wizards out there!!

**Comment by cecemf** [comment]
that would be great, even more when Kodi 14.2 is the a bug fix and shouldn't require more work to adapt it to SLICE.

Also things seem slow on GitHub regarding problem solving.

**Comment by cecemf** [comment]
The next stable version will come with Kodi 15

**Comment by ninyule** [comment]
This has now been done as of 18/10/15 so I am closing this issue
