### ISSUE TITLE
Fast Fowarding or Rewinding in music and videos

### ISSUE THREAD

**Issue by Blkwolf89** [FiveNinjas/SliceOS#27]
when I play a video and hit the fast forward or rewind and than I push play/pause as it fast forwarding it pauses it instead of plays is this what its should be doing or am I missing something thanks.

**Comment by gerv** [comment]
Yes, I see this also. I don't think it should be doing this - the Play/Pause button should take you out of FF and start playback. At the moment, it seems like it hangs (because it's paused) which is a jarring experience.

**Comment by ghollingworth** [comment]
That is the standard functionality of Kodi...  I'm not sure if it is possible to change this

**Comment by gerv** [comment]
I'm fairly sure that's not true, or if it's true, it's not been true for long. My previous XBMC/Kodi installation did this right.

**Comment by ghollingworth** [comment]
Basically for Kodi there are two keyboard buttons, Play (p) and Pause / Play (space)

We map the button to (space) because (p) doesn't work for pausing!

It may be possible to easily change the operation of Pause/Play whilst playing at speeds != 1

Gordon

**Comment by gerv** [comment]
Yep, that sounds like the right solution.

**Comment by ghollingworth** [comment]
Fixed
