### ISSUE TITLE
Can't enter IP address in System - OpenElec Settings - Connections

### ISSUE THREAD

**Issue by mod38** [FiveNinjas/SliceOS#3]
I tried to enter a fixed IP address for the Slice but it won't accept 192.168.1.xxx because it won't accept the 1 on its own in the third triplet. The usual workaround for this is to enter 001 but on entry of a 0 it just jumps ahead.  
The Disconnect, Edit, Cancel and Save legends from the previous menu are also shown at the bottom of the screen but not actually accessible.

**Comment by ghollingworth** [comment]
As a short term fix you could enter any old number then edit the configuration directly from a local computer by going to the samba shares (windows file sharing should work on Mac or Windows) then searching for the number you entered (or just search for 192) in the ConfigFiles or Userdata shares

Will have a look soon otherwise

**Comment by mod38** [comment]
Have searched all the files in Configfiles and Userdata but no sign of an IP address or any reference to network or connection - or dhcp for that matter. I can live with the situation for the moment so just take it that I am pointing out a non-functioning item on the interface.

**Comment by ghollingworth** [comment]
OK, not sure where that is stored... Must be in /storage somewhere! if you know how to ssh into the box you could try

grep -r 192 .*

I'll have a look at the interface sometime, but just trying to get you going again

**Comment by mod38** [comment]
./.cache/connman/wifi_b4eeb47abfb7_686f6d65_managed_psk/settings seems to be where the info is held. Is this a persistent file through reboot? 
![slice04](https://cloud.githubusercontent.com/assets/11555722/6735238/f18b806c-ce54-11e4-96d4-38685833deb8.jpg)
What editor (if any) is included with OpenELEC and can I just change "DHCP" to "MANUAL" and adjust the IP address?

**Comment by ghollingworth** [comment]
Yes this is persistent, not the easiest of files to edit though, I'd thought you'd be able to set it to static using some random number and then change it here, but of course you can't then ssh into the box afterwards!

Will have to check with our skinning dude...

Gordon

**Comment by mod38** [comment]
Thanks, I'll wait and see how it resolves.

**Comment by ghollingworth** [comment]
This has been fixed and rolled into the current nightly build

20150322080857

Can you please try updating and repeat?  If it works for you can you please close the issue

Thanks @pecinko @mod38

**Comment by mod38** [comment]
I downloaded the nightly build and the arrows do now work as expected. Thank you! 
I'll close the issue now.
