### ISSUE TITLE
Unable to build from source as Kodi 15.0 rc3 removed from OE sources

### ISSUE THREAD

**Issue by MikeBuzz** [FiveNinjas/SliceOS#31]
getting the following when building from source

--2015-08-20 13:54:13--  http://sources.openelec.tv/mirror/kodi/kodi-15.0-rc3-284f66a.tar.xz
Resolving sources.openelec.tv (sources.openelec.tv)... 82.220.2.33
Connecting to sources.openelec.tv (sources.openelec.tv)|82.220.2.33|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2015-08-20 13:54:13 ERROR 404: Not Found.

**Comment by ghollingworth** [comment]
Sounds about right....  Welcome to my world, I have to fix things like this everytime I update from the latest OpenELEC sources.

I'd suggest manipulating the revision in packages/mediacenter/kodi/package.mk so it tries to load one that _does_ exist preferably as close as possible to rc3 to avoid having to fix up any patches...

Will be moving to the stable branch soon (hopefully soon) and creating a new stable build so this should be averted in future but for the moment we're working on the master branch which is somewhat subject to commit churn...

Gordon

**Comment by MikeBuzz** [comment]
Yeah i am building to the release version of Kodi 15 at the moment, i will test 15.1 once the build completes

Do you know if there is any chance of OE taking on Slice as official project?

**Comment by MikeBuzz** [comment]
Also just noticed when you do a build from source the config.txt is the orignal OE version and not the Slice version with the overclock options enabled

**Comment by ghollingworth** [comment]
Ah, thanks mike, there is a script somewhere that copies the config.txt in from somewhere, it looks like it also needs adjusting to take the one from the project directory...

it'll either be something in scripts/image or in packages/tools/bcm2835-bootloader/

Gordon

**Comment by ghollingworth** [comment]
Also on another note, if you are able to update successfully this way I'll add more details for people to update their boxes without using the recovery mechanism...

**Comment by MikeBuzz** [comment]
i guess here is the cause of the config.txt being over written

BOOTLOADER_DIR=`find $PACKAGES -type d -name $BOOTLOADER 2>/dev/null`
        if [ -d "$BOOTLOADER_DIR"/files/3rdparty/bootloader/ ]; then
          cp -PR $BOOTLOADER_DIR/files/3rdparty/bootloader/\* $RELEASE_DIR/${DISTRONAME}_${PROJECT}/System
        fi

I updated last night using the drag and drop to update share and all worked as it does with OE

**Comment by MikeBuzz** [comment]
think there something more to the issue than the above. seems to be something relating to updating using samba share, when updating from stable to build from GIT things like dt-blob.bin.bak are missing from /flash, need to check the update script

**Comment by ghollingworth** [comment]
Now fixed...
