### ISSUE TITLE
Fix LED patterns

### ISSUE THREAD

**Issue by ghollingworth** [FiveNinjas/SliceOS#6]
Currently many of the patterns are not correct or need significant improvement...

@guru @lowfatcode @cooltempo @jimbojr

**Comment by Bleep42** [comment]
swapping over the two bitmaps 'sleep' and 'skipf' and then flip left to right 'skipr' will give you a good start point.

**Comment by guru** [comment]
They look pretty sweet now. So shiny :D

**Comment by ghollingworth** [comment]
Checked into nightly release
